kind: Service
apiVersion: v1
metadata:
  name: inventor
  {{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  labels:
    app: inventor
    type: backend
spec:
  selector:
    app: inventor
    type: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
